-- SQL to extract consolidated BW Objects Inventory from HANA DB:

SELECT 'ADSOs' AS OBJECT_TYPE, COUNT(*) AS CNT
FROM RSOADSO WHERE OBJVERS = 'A'

UNION ALL

SELECT 'InfoCubes', COUNT(*)
FROM RSDCUBE WHERE OBJVERS = 'A'

UNION ALL

SELECT 'Classic DSOs', COUNT(*)
FROM RSDODSO WHERE OBJVERS = 'A'

UNION ALL

SELECT 'BW Queries', COUNT(*)
FROM RSZCOMPDIR 
WHERE OBJVERS = 'A' AND COMPTYPE = 'QUERY'

UNION ALL

SELECT 'Transformations', COUNT(*)
FROM RSTRAN WHERE OBJVERS = 'A'

UNION ALL

SELECT 'DTPs', COUNT(*)
FROM RSBKDTP WHERE OBJVERS = 'A'

UNION ALL

SELECT 'Process Chains', COUNT(*)
FROM RSPCCHAIN WHERE OBJVERS = 'A';
